<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">


	<!-- Things that are needed only for Gazebo (not the physical robot). These include sensor and controller plugin specifications
	<xacro:include filename="$(find quadruped_description)/urdfs/trunk/trunk.gazebo.xacro"/>-->

	<!-- ================================ Arm ================================ -->
	<xacro:macro name="arm" params="prefix reflect">

  <!-- Joints -->
  <joint name="${prefix}_shoulder_pitch_joint" type="fixed">
    <origin xyz="${reflect*(shoulder_w/2+shoulder_pitch_l/2)} 0 0"/>
    <parent link="shoulder"/>
    <child link="${prefix}_shoulder_pitch_cylinder"/>
    <axis xyz="1 0 0"/>
    <limit effort="${joint_limit_effort}" velocity="${joint_velocity}" lower="-3.14" upper="3.14"/>
  </joint>

	<joint name="${prefix}_shoulder_roll_joint" type="fixed">
    <origin xyz="${reflect*(shoulder_roll_r+shoulder_pitch_l/2)} 0 0"  rpy="0 ${-reflect*0.3} 0"/>
    <parent link="${prefix}_shoulder_pitch_cylinder"/>
    <child link="${prefix}_shoulder_roll_cylinder"/>
    <axis xyz="0 1 0"/>
    <limit effort="${joint_limit_effort}" velocity="${joint_velocity}" lower="-3.14" upper="3.14"/>
  </joint>

	<joint name="${prefix}_shoulder_fixed_joint" type="fixed">
    <origin xyz="0 0 -${shoulder_roll_r+shoulder_bwn_l/2}"/>
    <parent link="${prefix}_shoulder_roll_cylinder"/>
    <child link="${prefix}_shoulder_bwn_cylinder"/>
  </joint>

	<joint name="${prefix}_shoulder_yaw_joint" type="fixed">
    <origin xyz="0 0 -${shoulder_bwn_l/2+shoulder_yaw_l/2}"/>
    <parent link="${prefix}_shoulder_bwn_cylinder"/>
    <child link="${prefix}_shoulder_yaw_cylinder"/>
    <axis xyz="0 0 1"/>
    <limit effort="${joint_limit_effort}" velocity="${joint_velocity}" lower="-3.14" upper="3.14"/>
  </joint>

	<joint name="${prefix}_elbow_joint" type="fixed">
    <origin xyz="0 0 -${elbow_r+shoulder_yaw_l/2}" rpy="0 ${reflect*0.3} 0"/>
    <parent link="${prefix}_shoulder_yaw_cylinder"/>
    <child link="${prefix}_elbow_cylinder"/>
    <axis xyz="0 1 0"/>
    <limit effort="${joint_limit_effort}" velocity="${joint_velocity}" lower="-3.14" upper="3.14"/>
  </joint>

	<joint name="${prefix}_forearm_fixed_joint" type="fixed">
    <origin xyz="0 0 -${elbow_r+forearm_l/2}" />
    <parent link="${prefix}_elbow_cylinder"/>
    <child link="${prefix}_forearm_cylinder"/>
  </joint>

	<joint name="${prefix}_wrist_joint" type="fixed">
    <origin xyz="0 0 -${forearm_l/2+wrist_l/2}"/>
    <parent link="${prefix}_forearm_cylinder"/>
    <child link="${prefix}_wrist_cylinder"/>
    <axis xyz="0 0 1"/>
    <limit effort="${joint_limit_effort}" velocity="${joint_velocity}" lower="-3.14" upper="3.14"/>
  </joint>

	<joint name="${prefix}_gripper_fixed_joint" type="fixed">
    <origin xyz="0 0 -${wrist_l/2+0.01}"/>
    <parent link="${prefix}_wrist_cylinder"/>
    <child link="${prefix}_gripper_fixed_link"/>
  </joint>

	<joint name="${prefix}_finger_joint1" type="fixed">
      <parent link="${prefix}_gripper_fixed_link"/>
      <child link="${prefix}_gripper_finger_link1"/>
      <origin xyz="0.0 0 0" />
      <axis xyz="1 0 0" />
      <limit effort="1" lower="-0.09" upper="0" velocity="1.0"/>
  </joint>

	<joint name="${prefix}_finger_joint2" type="fixed">
      <parent link="${prefix}_gripper_fixed_link"/>
      <child link="${prefix}_gripper_finger_link2"/>
      <origin xyz="0.0 0 0" />
      <axis xyz="1 0 0" />
      <limit effort="1" lower="0" upper="0.09" velocity="1.0"/>
  </joint>


  <!-- Links -->
  <link name="${prefix}_shoulder_pitch_cylinder">
    <visual>
      <geometry>
        <cylinder radius="${shoulder_pitch_r}" length="${shoulder_pitch_l}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 ${PI_2} 0"/>
      <material name="red"/>
    </visual>
    <collision>
			<origin xyz="0 0 0" rpy="0 ${PI_2} 0"/>
      <geometry>
        <cylinder radius="${shoulder_pitch_r}" length="${shoulder_pitch_l}"/>
      </geometry>
    </collision>
  </link>

  <link name="${prefix}_shoulder_roll_cylinder">
    <visual>
      <geometry>
        <cylinder radius="${shoulder_roll_r}" length="${shoulder_roll_l}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="${PI_2} 0 0"/>
      <material name="red"/>
    </visual>
    <collision>
			<origin xyz="0 0 0" rpy="${PI_2} 0 0"/>
      <geometry>
        <cylinder radius="${shoulder_roll_r}" length="${shoulder_roll_l}"/>
      </geometry>
    </collision>
  </link>

  <link name="${prefix}_shoulder_bwn_cylinder">
    <visual>
      <geometry>
        <cylinder radius="${shoulder_bwn_r}" length="${shoulder_bwn_l}"/>
      </geometry>
      <origin xyz="0 0 0"/>
      <material name="red"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${shoulder_bwn_r}" length="${shoulder_bwn_l}"/>
      </geometry>
    </collision>
  </link>

  <link name="${prefix}_shoulder_yaw_cylinder">
    <visual>
      <geometry>
        <cylinder radius="${shoulder_yaw_r}" length="${shoulder_yaw_l}"/>
      </geometry>
      <origin xyz="0 0 0"/>
      <material name="red"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${shoulder_yaw_r}" length="${shoulder_yaw_l}"/>
      </geometry>
    </collision>
  </link>

  <link name="${prefix}_elbow_cylinder">
    <visual>
      <geometry>
        <cylinder radius="${elbow_r}" length="${elbow_l}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="${PI_2} 0 0"/>
      <material name="red"/>
    </visual>
    <collision>
			<origin xyz="0 0 0" rpy="${PI_2} 0 0"/>
      <geometry>
        <cylinder radius="${elbow_r}" length="${elbow_l}"/>
      </geometry>
    </collision>
  </link>

  <link name="${prefix}_forearm_cylinder">
    <visual>
      <geometry>
        <cylinder radius="${forearm_r}" length="${forearm_l}"/>
      </geometry>
      <origin xyz="0 0 0"/>
      <material name="red"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${forearm_r}" length="${forearm_l}"/>
      </geometry>
    </collision>
  </link>

  <link name="${prefix}_wrist_cylinder">
    <visual>
      <geometry>
        <cylinder radius="${wrist_r}" length="${wrist_l}"/>
      </geometry>
      <origin xyz="0 0 0"/>
      <material name="red"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wrist_r}" length="${wrist_l}"/>
      </geometry>
    </collision>
  </link>

  <link name="${prefix}_gripper_fixed_link">
    <visual>
      <geometry>
        <box size="0.2 0.07 0.02"/>
      </geometry>
      <origin xyz="0 0 0"/>
      <material name="red"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.2 0.07 0.02"/>
      </geometry>
    </collision>
  </link>

  <link name="${prefix}_gripper_finger_link1">
    <visual>
      <geometry>
        <box size="0.02 0.07 0.2"/>
      </geometry>
      <origin xyz="0.09 0 -0.1" />
      <material name="red"/>
    </visual>
    <collision>
			<origin xyz="0.09 0 -0.1" />
      <geometry>
        <box size="0.02 0.07 0.2"/>
      </geometry>
    </collision>
  </link>

  <link name="${prefix}_gripper_finger_link2">
    <visual>
      <geometry>
        <box size="0.02 0.07 0.2"/>
      </geometry>
      <origin xyz="-0.09 0 -0.1"/>
      <material name="red"/>
    </visual>
    <collision>
			<origin xyz="-0.09 0 -0.1"/>
      <geometry>
        <box size="0.02 0.07 0.2"/>
      </geometry>
    </collision>
  </link>

  </xacro:macro>

</robot>
